import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, '..')
const envPath = path.join(root, '.env.local')
const outPath = path.join(root, 'public', 'firebase-messaging-sw.js')

const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
const FIREBASE_CDN = String(pkg.dependencies?.firebase ?? '12.12.0').replace(/^[\^~]/, '')

/** @param {string} key */
function readEnv(key) {
  if (!fs.existsSync(envPath)) return ''
  const text = fs.readFileSync(envPath, 'utf8')
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(new RegExp(`^\\s*${key}\\s*=\\s*(.+)$`))
    if (!m) continue
    let v = m[1].trim()
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
      v = v.slice(1, -1)
    }
    return v
  }
  return ''
}

const firebaseConfig = {
  apiKey: readEnv('VITE_FIREBASE_API_KEY'),
  authDomain: readEnv('VITE_FIREBASE_AUTH_DOMAIN'),
  projectId: readEnv('VITE_FIREBASE_PROJECT_ID'),
  storageBucket: readEnv('VITE_FIREBASE_STORAGE_BUCKET'),
  messagingSenderId: readEnv('VITE_FIREBASE_MESSAGING_SENDER_ID'),
  appId: readEnv('VITE_FIREBASE_APP_ID'),
  measurementId: readEnv('VITE_FIREBASE_MEASUREMENT_ID') || undefined,
}

if (!firebaseConfig.apiKey || !firebaseConfig.projectId || !firebaseConfig.appId) {
  console.warn('[inject-fcm-sw] .env.local eksik — firebase-messaging-sw.js boş anahtarlarla yazılacak.')
}

const sw = `/* Auto-generated by scripts/inject-fcm-sw.mjs — elle düzenlemeyin */
/* Generated: ${new Date().toISOString()} */
importScripts('https://www.gstatic.com/firebasejs/${FIREBASE_CDN}/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/${FIREBASE_CDN}/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(firebaseConfig, null, 2)});

const messaging = firebase.messaging();

function resolveNotificationUrl(data) {
  const link = data && typeof data.link === 'string' ? data.link.trim() : '';
  if (!link) return '/dashboard';
  if (link.startsWith('http://') || link.startsWith('https://')) return link;
  return link.startsWith('/') ? link : '/' + link;
}

messaging.onBackgroundMessage((payload) => {
  const data = payload.data || {};
  const title =
    payload.notification?.title ||
    (typeof data.title === 'string' ? data.title : '') ||
    '[ AUDAZ ] BİLDİRİM';
  const body =
    payload.notification?.body ||
    (typeof data.message === 'string' ? data.message : '') ||
    '';
  const link = resolveNotificationUrl(data);
  const tag = data.notificationId || data.docId || data.type || 'audaz-notification';

  self.registration.showNotification(title, {
    body,
    icon: '/logo.png',
    badge: '/logo.png',
    data: { ...data, link },
    tag: String(tag),
  });
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const targetUrl = resolveNotificationUrl(event.notification?.data || {});
  const absoluteUrl = targetUrl.startsWith('http')
    ? targetUrl
    : self.location.origin + targetUrl;

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ('focus' in client) {
          if ('navigate' in client) {
            return client.navigate(absoluteUrl).then(() => client.focus());
          }
          client.focus();
          return client;
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(absoluteUrl);
      }
      return undefined;
    }),
  );
});
`

fs.mkdirSync(path.dirname(outPath), { recursive: true })
fs.writeFileSync(outPath, sw, 'utf8')
console.log('[inject-fcm-sw] public/firebase-messaging-sw.js güncellendi.')
