import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, '..')
const envPath = path.join(root, '.env.local')
const outPath = path.join(root, 'public', 'firebase-messaging-sw.js')

const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
const FIREBASE_CDN = String(pkg.dependencies?.firebase ?? '12.12.0').replace(/^[\^~]/, '')

const ENV_KEYS = {
  apiKey: 'VITE_FIREBASE_API_KEY',
  authDomain: 'VITE_FIREBASE_AUTH_DOMAIN',
  projectId: 'VITE_FIREBASE_PROJECT_ID',
  storageBucket: 'VITE_FIREBASE_STORAGE_BUCKET',
  messagingSenderId: 'VITE_FIREBASE_MESSAGING_SENDER_ID',
  appId: 'VITE_FIREBASE_APP_ID',
  measurementId: 'VITE_FIREBASE_MEASUREMENT_ID',
}

/** @param {string} key */
function readEnvFile(key) {
  if (!fs.existsSync(envPath)) return ''
  const text = fs.readFileSync(envPath, 'utf8')
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(new RegExp(`^\\s*${key}\\s*=\\s*(.+)$`))
    if (!m) continue
    let v = m[1].trim()
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
      v = v.slice(1, -1)
    }
    return v.trim()
  }
  return ''
}

/**
 * Vercel/CI: process.env.VITE_* — yerel: .env.local yedek.
 * @param {string} key
 */
function readEnv(key) {
  const fromProcess = process.env[key]
  if (fromProcess && String(fromProcess).trim()) {
    return String(fromProcess).trim()
  }
  return readEnvFile(key)
}

/** @returns {Record<string, string>} */
function buildFirebaseConfig() {
  /** @type {Record<string, string>} */
  const config = {}

  for (const [field, envKey] of Object.entries(ENV_KEYS)) {
    const value = readEnv(envKey)
    if (value) config[field] = value
  }

  const projectId = config.projectId ?? ''
  if (projectId && !config.authDomain) {
    config.authDomain = `${projectId}.firebaseapp.com`
  }
  if (projectId && !config.storageBucket) {
    config.storageBucket = `${projectId}.firebasestorage.app`
  }

  return config
}

const firebaseConfig = buildFirebaseConfig()

const REQUIRED_FIELDS = ['apiKey', 'projectId', 'appId', 'messagingSenderId']
const missingFields = REQUIRED_FIELDS.filter((field) => !firebaseConfig[field])

if (missingFields.length > 0) {
  console.error('[inject-fcm-sw] Firebase service worker config eksik:', missingFields.join(', '))
  console.error(
    '[inject-fcm-sw] VITE_FIREBASE_* değişkenlerini .env.local veya Vercel Environment Variables içinde tanımlayın.',
  )
  process.exit(1)
}

const configJson = JSON.stringify(firebaseConfig, null, 2)

const sw = `/* Auto-generated by scripts/inject-fcm-sw.mjs — elle düzenlemeyin */
/* Generated: ${new Date().toISOString()} */
importScripts('https://www.gstatic.com/firebasejs/${FIREBASE_CDN}/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/${FIREBASE_CDN}/firebase-messaging-compat.js');

const firebaseConfig = ${configJson};

if (!firebaseConfig.projectId || !firebaseConfig.apiKey || !firebaseConfig.appId) {
  console.error(
    '[AUDAZ SW] Firebase config eksik — projectId:',
    firebaseConfig.projectId || '(boş)',
  );
} else {
  firebase.initializeApp(firebaseConfig);

  const messaging = firebase.messaging();

  function resolveNotificationUrl(data) {
    const link = data && typeof data.link === 'string' ? data.link.trim() : '';
    if (!link) return '/dashboard';
    if (link.startsWith('http://') || link.startsWith('https://')) return link;
    return link.startsWith('/') ? link : '/' + link;
  }

  messaging.onBackgroundMessage((payload) => {
    const data = payload.data || {};
    const title =
      payload.notification?.title ||
      (typeof data.title === 'string' ? data.title : '') ||
      '[ AUDAZ ] BİLDİRİM';
    const body =
      payload.notification?.body ||
      (typeof data.message === 'string' ? data.message : '') ||
      '';
    const link = resolveNotificationUrl(data);
    const tag = data.notificationId || data.docId || data.type || 'audaz-notification';

    self.registration.showNotification(title, {
      body,
      icon: '/logo.png',
      badge: '/logo.png',
      data: { ...data, link },
      tag: String(tag),
    });
  });

  self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    const targetUrl = resolveNotificationUrl(event.notification?.data || {});
    const absoluteUrl = targetUrl.startsWith('http')
      ? targetUrl
      : self.location.origin + targetUrl;

    event.waitUntil(
      clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
        const sameOriginClients = clientList.filter((client) => {
          try {
            return new URL(client.url).origin === self.location.origin;
          } catch {
            return false;
          }
        });

        for (const client of sameOriginClients) {
          if ('focus' in client) {
            if ('navigate' in client) {
              return client.navigate(absoluteUrl).then(() => client.focus());
            }
            client.focus();
            return client;
          }
        }

        if (clients.openWindow) {
          return clients.openWindow(absoluteUrl);
        }
        return undefined;
      }),
    );
  });
}
`

fs.mkdirSync(path.dirname(outPath), { recursive: true })
fs.writeFileSync(outPath, sw, 'utf8')
console.log(
  `[inject-fcm-sw] public/firebase-messaging-sw.js güncellendi (projectId: ${firebaseConfig.projectId}).`,
)
